# CONFIGURATION FILE

# Priority scoring weights
URGENCY_HIGH = 40
URGENCY_MEDIUM = 25
URGENCY_LOW = 10

MEDICAL_BONUS = 20

OLD_REQUEST_24H = 25
OLD_REQUEST_12H = 15
OLD_REQUEST_6H  = 10

HIGH_FULFILMENT_BONUS = 10
LOW_FULFILMENT_PENALTY = -10

DUPLICATE_PENALTY = -30

# Matching configuration
TOP_N = 15
USAGE_PENALTY_WEIGHT = 15
MAX_DONOR_REUSE = 3

# Randomness (for fairness)
RANDOMNESS_MIN = 0
RANDOMNESS_MAX = 5
RANDOM_SEED = 42

# Fallback
ENABLE_FALLBACK = True